# Tasca4_exercici1

Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [11]:
import numpy as np

arry = np.array([[1,2,3,4,5,6], [1,2,3,4,5,6]])

def stadistic_sumarise(matrix):
    print('Resum estadistic de la matriu')
    #print ('La mitjana es: ',matrix.mean())# media
    print ('La mediana es: ',np.median(matrix)) #mediana
    print ('La desviació es: ', np.std(matrix)) #Desviación atipica
    print ('La variació es: ', np.var(matrix)) #Varianza 
    print('La correlacción de datos: ',np.corrcoef(matrix))
    print('El maximo del Array:', np.max(matrix))
    print('El minimo del array:', np.min(matrix))
   
    if arry.ndim > 1 :
        print('ERROr: Esta matriz tiene mas de ', arry.ndim )
    

stadistic_sumarise(arry)


Resum estadistic de la matriu
La mediana es:  3.5
La desviació es:  1.707825127659933
La variació es:  2.9166666666666665
La correlacción de datos:  [[1. 1.]
 [1. 1.]]
El maximo del Array: 6
El minimo del array: 1
ERRor: Esta ,atriz tiene mas de  2


# Tasca4_exercici2

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100

In [108]:
def sqrt_random_numbers(N):
    print('array ', N)
    return N * N
    
sqrt_random_numbers(N = np.random.randint(100 ,size=2))

array  [24 17]


array([576, 289])

# Tasca4_exercici3

Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna

In [107]:
myarr2 = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
print('suma columnes matriu ', np.apply_along_axis(sum, 0 ,myarr2))
print ('Suma files matriu ',  np.apply_along_axis(sum, 1 , myarr2))

suma columnes matriu  [ 2  4  6  8 10 12]
Suma files matriu  [21 21]


# Tasca4_exercici4

Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

Quan generen els models hem de veure si tenim un coeficient de correlació massa baix o massa alt (prop d’1 sería l’ideal).

In [123]:
myarr3 = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])

def Coe_correlacio(matrix):
        return np.corrcoef(matrix)

print(Coe_correlacio(myarr3))

    

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
